### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by 5P4D3** [BuffaloWill/oxml_xxe#16]
```
$ ruby server.rb 
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- haml (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from server.rb:4:in `<main>'
```

Whats the problem here?

**Comment by GennadySpb** [comment]
Hello! Try run in your work dir:

$ gem install haml



вт, 2 мая 2017 г. в 8:58, 5P4D3 <notifications@github.com>:

**Comment by 5P4D3** [comment]
```
$ ruby server.rb 
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- data_mapper (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/spade/Documents/CustomTools/oxml_xxe/model/master.rb:2:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from server.rb:11:in `<main>'

```

After installing haml.. another error comes up..

**Comment by GennadySpb** [comment]
So, continue install gems.
See line 'cannot load such file -- data_mapper (LoadError)' - that speaks
about absent "data_mapper".

gem install data_mapper


вт, 2 мая 2017 г. в 9:13, 5P4D3 <notifications@github.com>:

**Comment by 5P4D3** [comment]
```
$ruby server.rb 
/usr/lib/ruby/2.3.0/rubygems/specification.rb:2287:in `raise_if_conflicts': Unable to activate dm-serializer-1.2.2, because json-2.0.1 conflicts with json (~> 1.6) (Gem::ConflictError)
	from /usr/lib/ruby/2.3.0/rubygems/specification.rb:1408:in `activate'
	from /usr/lib/ruby/2.3.0/rubygems/specification.rb:1442:in `block in activate_dependencies'
	from /usr/lib/ruby/2.3.0/rubygems/specification.rb:1428:in `each'
	from /usr/lib/ruby/2.3.0/rubygems/specification.rb:1428:in `activate_dependencies'
	from /usr/lib/ruby/2.3.0/rubygems/specification.rb:1410:in `activate'
	from /usr/lib/ruby/2.3.0/rubygems.rb:196:in `rescue in try_activate'
	from /usr/lib/ruby/2.3.0/rubygems.rb:193:in `try_activate'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:125:in `rescue in require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /home/spade/Documents/CustomTools/oxml_xxe/model/master.rb:2:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from server.rb:11:in `<main>'
```

Now it says a conflict thingy..

**Comment by BuffaloWill** [comment]
@5P4D3, you have an unsupported Ruby version (2.3.0). oxml_xxe only supports 2.1.5. 

I would suggest RVM as discussed in the README.md:
```
rvm install 2.1.5
rvm use 2.1.5
```

**Comment by 5P4D3** [comment]
okay got it..
