### ISSUE TITLE
Gemfile outdated

### ISSUE THREAD

**Issue by noraj** [BuffaloWill/oxml_xxe#30]
Gemfile use ruby 2.3.5 but this version is old an it is not possible to build it easily anymore n modern distro. I tried building 2.3.5 and 2.3.8 with rbenv and it fails.

I tried to install dependencies with ruby 2.6.2 but in the gemfile some versions were not fixed:

```
gem 'sinatra', '1.4.8'
gem 'haml'
gem 'rubyzip'
gem 'json','1.8.6' 
gem 'nokogiri'
gem 'data_mapper', '1.2.0'
gem 'dm-sqlite-adapter', '1.2.0'
```

So breaking changes happened between 2017 and 2019 for some of them.

```
$ ruby server.rb                                                                                                                                                                                
Traceback (most recent call last):                                                                                                                                                              
        5: from server.rb:11:in `<main>'                                                                                                                                                        
        4: from /home/noraj/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'                                                                            
        3: from /home/noraj/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'                                                                            
        2: from /home/noraj/Tools/oxml_xxe/model/master.rb:2:in `<top (required)>'                                                                                                              
        1: from /home/noraj/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'                                                                            
/home/noraj/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- data_mapper (LoadError)                                          
        12: from server.rb:11:in `<main>'                                                                                                                                                       
        11: from /home/noraj/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'                                                                           
        10: from /home/noraj/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'                                                                           
         9: from /home/noraj/Tools/oxml_xxe/model/master.rb:2:in `<top (required)>'                                                                                                             
         8: from /home/noraj/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'                                                                           
         7: from /home/noraj/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:123:in `rescue in require'                                                                
         6: from /home/noraj/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems.rb:217:in `try_activate'                                                                                             
         5: from /home/noraj/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/specification.rb:1420:in `activate'
         4: from /home/noraj/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `activate_dependencies'
         3: from /home/noraj/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `each'
         2: from /home/noraj/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/specification.rb:1452:in `block in activate_dependencies'
         1: from /home/noraj/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/specification.rb:1418:in `activate'
/home/noraj/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/specification.rb:2302:in `raise_if_conflicts': Unable to activate dm-serializer-1.2.2, because json-2.1.0 conflicts with json (~> 1.6)
 (Gem::ConflictError)                           
        13: from server.rb:11:in `<main>'       
        12: from /home/noraj/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        11: from /home/noraj/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        10: from /home/noraj/Tools/oxml_xxe/model/master.rb:2:in `<top (required)>'             
         9: from /home/noraj/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
         8: from /home/noraj/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:123:in `rescue in require'
         7: from /home/noraj/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems.rb:216:in `try_activate'
         6: from /home/noraj/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems.rb:223:in `rescue in try_activate'
         5: from /home/noraj/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/specification.rb:1420:in `activate'
         4: from /home/noraj/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `activate_dependencies'
         3: from /home/noraj/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `each'
         2: from /home/noraj/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/specification.rb:1452:in `block in activate_dependencies'
         1: from /home/noraj/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/specification.rb:1418:in `activate'
/home/noraj/.rbenv/versions/2.6.2/lib/ruby/2.6.0/rubygems/specification.rb:2302:in `raise_if_conflicts': Unable to activate dm-serializer-1.2.2, because json-2.1.0 conflicts with json (~> 1.6)
 (Gem::ConflictError)
```
So if you can update dependencies and test with a 2.6.x ruby.

**Comment by noraj** [comment]
I PR in #33 waiting for a dependency update

**Comment by b1nslashsh** [comment]
@noraj have you fixed this! 
am still getting same error

**Comment by b1nslashsh** [comment]
NVM downgraded to ruby version 6.3.5 and used old Gemfile
```
source 'https://rubygems.org'

ruby "2.3.5"

gem 'sinatra', '1.4.8'
gem 'haml'
gem 'rubyzip'
gem 'json','1.8.6' 
gem 'nokogiri'
gem 'data_mapper', '1.2.0'
gem 'dm-sqlite-adapter', '1.2.0'
```

**Comment by BuffaloWill** [comment]
This should be fixed now =)

**Comment by noraj** [comment]
Ruby 2.7 is deprecated cf. https://www.ruby-lang.org/en/downloads/branches/ and https://endoflife.date/ruby, why not updating to 3.2 directly?

**Comment by BuffaloWill** [comment]
doh! I missed that. Thank you @noraj. I will test out a 3.2 branch and get it pushed.

**Comment by BuffaloWill** [comment]
Done.
