### ISSUE TITLE
Docker Image - Error while starting web server - missing gems

### ISSUE THREAD

**Issue by FelSec** [BuffaloWill/oxml_xxe#49]
When attempting to build and run the latest version of the tool, the docker image builds correctly but is unable to run.

The log output states that it is unable to find the gem dependencies. See below.

```
λ docker-compose up --build                                                                   0 (01:09.004) < 13:33:55
Building web
[+] Building 0.8s (11/11) FINISHED
 => [internal] load build definition from Dockerfile                                                                0.0s
 => => transferring dockerfile: 366B                                                                                0.0s
 => [internal] load .dockerignore                                                                                   0.0s
 => => transferring context: 2B                                                                                     0.0s
 => [internal] load metadata for docker.io/library/ruby:3.2.2-slim                                                  0.7s
 => [1/6] FROM docker.io/library/ruby:3.2.2-slim@sha256:995aeea8fd8261662d7d9c157ca319ce009c7f99333b3358eb26e84b63  0.0s
 => [internal] load build context                                                                                   0.0s
 => => transferring context: 19.16kB                                                                                0.0s
 => CACHED [2/6] RUN apt-get update &&     apt-get install -y make git libsqlite3-dev libxslt-dev libxml2-dev zlib  0.0s
 => CACHED [3/6] WORKDIR /oxml_xxe                                                                                  0.0s
 => CACHED [4/6] COPY Gemfile ./                                                                                    0.0s
 => CACHED [5/6] RUN bundle install                                                                                 0.0s
 => CACHED [6/6] COPY . .                                                                                           0.0s
 => exporting to image                                                                                              0.0s
 => => exporting layers                                                                                             0.0s
 => => writing image sha256:adb7d84f06b69380dcc7e887c6fe1816a63bcad7925075b32df53cf49757d442                        0.0s
 => => naming to docker.io/library/oxml_xxe_web                                                                     0.0s
Starting oxml_xxe_web_1 ... done
Attaching to oxml_xxe_web_1
web_1  | /usr/local/lib/ruby/3.2.0/bundler/definition.rb:524:in `materialize': Could not find slim-5.1.0, nokogiri-1.14.3-x86_64-linux, sequel-5.68.0, sqlite3-1.6.2-x86_64-linux, temple-0.10.0, tilt-2.1.0, thor-1.2.1 in locally installed gems (Bundler::GemNotFound)
web_1  |        from /usr/local/lib/ruby/3.2.0/bundler/definition.rb:197:in `specs'
web_1  |        from /usr/local/lib/ruby/3.2.0/bundler/definition.rb:254:in `specs_for'
web_1  |        from /usr/local/lib/ruby/3.2.0/bundler/runtime.rb:18:in `setup'
web_1  |        from /usr/local/lib/ruby/3.2.0/bundler.rb:171:in `setup'
web_1  |        from /usr/local/lib/ruby/3.2.0/bundler/setup.rb:23:in `block in <top (required)>'
web_1  |        from /usr/local/lib/ruby/3.2.0/bundler/ui/shell.rb:159:in `with_level'
web_1  |        from /usr/local/lib/ruby/3.2.0/bundler/ui/shell.rb:111:in `silence'
web_1  |        from /usr/local/lib/ruby/3.2.0/bundler/setup.rb:23:in `<top (required)>'
web_1  |        from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
web_1  |        from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
web_1  |        from /usr/local/lib/ruby/3.2.0/rubygems.rb:1370:in `<top (required)>'
web_1  |        from <internal:gem_prelude>:2:in `require'
web_1  |        from <internal:gem_prelude>:2:in `<internal:gem_prelude>'
oxml_xxe_web_1 exited with code 1
```

**Comment by tarihub** [comment]
@FelSec PR has been merge ~

**Comment by BuffaloWill** [comment]
Thanks @tarihub

**Comment by BuffaloWill** [comment]
And @FelSec!

**Comment by FelSec** [comment]
No problem
